apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "fastapi-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80