apiVersion: v1
kind: Secret
metadata:
  name: fastapi-git-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: < github repo url (https) >
  username: < github username>
  password: < base64 encoded github password >
  type: git
