replicaCount: 1

image:
  repository: kola06/fastapi-app
  tag: "latest"  # ← this will be overwritten by GitHub Actions per build
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-cred

service:
  name: fastapi-service
  type: LoadBalancer
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: fastapi.local
      paths:
        - path: /
          pathType: Prefix
