replicaCount: 1

image:
  repository: kola06/fastapi-app
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
- name: dockerhub-cred

service:
  name: fastapi-service
  type: LoadBalancer
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  hosts:
  - host: fastapi.local
    paths:
    - path: /
      pathType: Prefix
