replicaCount: 1

image:
  repository: joviserrao/fastapi-app
  tag: "687e22f4a7dee487e13d3d5037b20639cda58dda"
  pullPolicy: IfNotPresent

imagePullSecrets:
- name: dockerhub-cred

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
  - host: fastapi.local
    paths:
    - path: /
      pathType: Prefix
