replicaCount: 1

image:
  repository: serrajov/fastapi-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
  - host: fastapi.local
    paths:
    - path: /
      pathType: Prefix
