name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "app-code/**"
      - "helm/**"
      - "!**.md"
      - "!additional-files/**"

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate image tag
      run: echo "TAG=fastapi-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app-code
        push: true
        tags: kola06/fastapi-app:${{ env.TAG }}

    - name: Update image tag in values.yaml
      run: |
        sed -i "s|tag: .*|tag: \"${{ env.TAG }}\"|" helm/fastapi-app/values.yaml

    - name: Commit updated Helm tag
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add helm/fastapi-app/values.yaml
        git commit -m "Update image tag to ${{ env.TAG }}"
        git push
