name: CI Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
         context: ./app-code
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    # - name: Set up Helm
    #   uses: azure/setup-helm@v3
    #   with:
    #     version: v3.12.0

    # - name: Configure Kubeconfig for Minikube
    #   run: |
    #     mkdir -p ~/.kube
    #     echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config

    # - name: Deploy using Helm
    #   run: |
    #     helm upgrade --install fastapi-app ./helm \
    #       --set image.repository=${{ secrets.DOCKER_USERNAME }}/fastapi-app \
    #       --set image.tag=latest \
    #       --namespace default